# gen_bringup.py
# Generates bringup.S from a configurable list of tests.
# Usage: python3 tests/bringup/gen_bringup.py

# ─────────────────────────────────────────────
#  CONFIGURE: list the tests you want to run,
#  in the order they should execute.
# ─────────────────────────────────────────────
TESTS = [
    # "add_test",
    # "or_test",
    # "and_test",
    # "sub_test",
    # "addi_test",
    # "subi_test",
    # "lw_test",
    # "sw_test",
    # "slt_test",
    # "xor_test",
    # "slti_test",
    # "xori_test",
    # "ori_test",
    # "andi_test",
    # "beq_test",
    # "jal_test",
    # "lui_test",
    # "auipc_test",
    # "sll_test",
    # "sra_test",
    # "srl_test",
    "sb_test",
    "lb_test",  # covers lbu
    "lh_test",  # covers lhu
    "sh_test",
    "bne_test",
    "blt_test",  # covers bltu
    "bge_test",  # covers bgeu
    "jalr_test",
]

# ─────────────────────────────────────────────
#  Fail code reference (for comments in output)
# ─────────────────────────────────────────────
FAIL_CODES = {
    "add_test": 300,
    "or_test": 100,
    "and_test": 200,
    "sub_test": 410,
    "addi_test": 400,
    "subi_test": 500,
    "lw_test": 600,
    "sw_test": 700,
    "slt_test": 800,
    "xor_test": 600,
    "slti_test": 810,
    "xori_test": 600,
    "ori_test": 820,
    "andi_test": 210,
    "beq_test": 1000,
    "jal_test": 1100,
    "lui_test": 1200,
    "auipc_test": 1300,
    "sll_test": 1350,
    "sra_test": 1450,
    "srl_test": 1400,
    "sb_test": 1600,
    "lb_test": 1700,
    "lh_test": 1800,
    "sh_test": 1900,
    "bne_test": 2000,
    "blt_test": 2100,
    "bge_test": 2200,
    "jalr_test": 2300,
}

OUTPUT_FILE = "tests/bringup/bringup.S"

# ─────────────────────────────────────────────────────────────────────────────


def return_label(test_name: str) -> str:
    """Convert 'add_test' -> 'return_add_test'."""
    return f"return_{test_name}"


def generate(tests: list[str], output_file: str) -> None:
    if not tests:
        raise ValueError("TESTS list is empty — nothing to generate.")

    lines: list[str] = []

    # ── Header ────────────────────────────────────────────────────────────────
    lines += [
        "// C Runtime entry point",
        "// Max Conine",
        "// mconine@g.hmc.edu",
        "// Auto-generated by gen_bringup.py",
        "",
    ]

    # ── .extern declarations ──────────────────────────────────────────────────
    for t in tests:
        lines.append(f".extern {t}")
    lines.append("")

    # ── .section / .globl declarations ───────────────────────────────────────
    lines += [
        " .section .text.init",
        " .globl main",
    ]
    for t in tests:
        lines.append(f" .globl {return_label(t)}")
    lines.append(" .type main, @function")
    lines.append("")

    # ── main entry ────────────────────────────────────────────────────────────
    lines += [
        "main:",
        f" j {tests[0]}",
        "",
    ]

    # ── return labels chaining tests together ─────────────────────────────────
    for i, t in enumerate(tests):
        next_target = tests[i + 1] if i + 1 < len(tests) else "pass"
        lines += [
            f"{return_label(t)}:",
            f" j {next_target}",
            "",
        ]

    # ── Fail-code reference comment ───────────────────────────────────────────
    lines.append("// Fail ranges:")
    for t in tests:
        if t in FAIL_CODES:
            # strip trailing "_test" for the comment label
            short = t.replace("_test", "")
            lines.append(f"// {short}: {FAIL_CODES[t]}")
    lines.append("")

    with open(output_file, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated '{output_file}' with {len(tests)} test(s): {', '.join(tests)}")


if __name__ == "__main__":
    generate(TESTS, OUTPUT_FILE)
